#!/bin/bash

. $(dirname $0)/../config.sh

if [ -z $1 ] ; then
  etape=replication
else
  etape=$1
fi

if [ "$1" == "" ] ; then
  echo "This tool computes timespent by one of those 2 steps : replication ou tile_expiry"
  echo "usage : ./infos_temps replication"
fi

i=0 
tot=0
for x in `grep $etape $work_dir/diff-update-timing | cut -f3 -d,` ; do 
  i=$(($i+1)) 
  tot=$(($tot+$x)) 
done 
echo "Step $etape took on average $(($tot/$i)) seconds"
